name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        node: ['14']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        submodules: true
      - run: git submodule update --init --recursive
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install nix 2.3.6
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://releases.nixos.org/nix/nix-2.3.6/install
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use maker and dapp cachix
        uses: cachix/cachix-action@v10
        with:
          name: maker
          extraPullNames: dapp

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-
      - run: nix-shell --run 'bash ./scripts/setup.sh'

      - run: yarn lint
      - run: yarn format
      - run: yarn build

      - run: yarn
      - run: ./scripts/build-infra.sh
      - run: ./scripts/run-infra.sh&
      - run: ./.github/workflows/wait-for-it.sh -h localhost -p 9545 -t 120 # wait for l1
      - run: ./.github/workflows/wait-for-it.sh -h localhost -p 8545 -t 120 # wait for l2
      - run: sleep 60 # give it some time to initialize

      - run: yarn test
      - run: yarn typecheck
      - run: .github/workflows/no-git-changes.sh
