name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        node: ['14']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install nix 2.3.6
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://releases.nixos.org/nix/nix-2.3.6/install
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use maker and dapp cachix
        uses: cachix/cachix-action@v10
        with:
          name: maker
          extraPullNames: dapp

      - run: yarn
      # - name: Cache Yarn dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       node_modules
      #       */*/node_modules
      #     key: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-
      - run: nix-shell --run 'bash ./scripts/setup.sh'

      - run: yarn lint
      - run: yarn format
      - run: yarn build

      - run: ./scripts/build-infra.sh
      - run: ./scripts/run-infra.sh&
      - run: yarn ts-node ./scripts/ensure-infra-up.ts
      - run: sleep 60 # give it some time to initialize

      - name: Create env file
        run: |
          touch .env
          echo ARBITRUM_L1_RPC_URL="${{ secrets.ARBITRUM_L1_RPC_URL }}" >> .env
          echo ARBITRUM_L2_RPC_URL="https://rinkeby.arbitrum.io/rpc" >> .env
          echo OPTIMISM_L1_RPC_URL="http://127.0.0.1:9545" >> .env
          echo OPTIMISM_L2_RPC_URL="http://127.0.0.1:8545" >> .env
          echo DEPLOYER_PRIV_KEY="${{ secrets.DEPLOYER_PRIV_KEY }}" >> .env
          echo USER_PRIV_KEY="${{ secrets.USER_PRIV_KEY }}" >> .env

      - run: yarn test:optimism
      - run: yarn test:arbitrum # todo: run in parallel
      - run: yarn typecheck
      - run: .github/workflows/no-git-changes.sh
