name: Submodule update

on:
  #schedule:
  #  # * is a special character in YAML so you have to quote this string
  #  - cron:  '0 12 * * *'
  # workflow_dispatch:
  pull_request:

jobs:
  submodule_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Git Submodule Update
        run: |
          ./scripts/bump-deps.sh

      - uses: peter-evans/create-pull-request@v3
        with:
          base: master
          branch: bump-submodules
          title: Bump submodules
          body: Automated PR created after out of date submodules were detected
          reviewers: krzkaczor
